#!/usr/bin/python3

import evdev

def detect_key_combination():
    devices = evdev.list_devices()
    for device in devices:
        if evdev.InputDevice(device).name == "AT Translated Set 2 keyboard":
            keyboard = evdev.InputDevice(device)
            break

    key_combo = [evdev.ecodes.KEY_LEFTCTRL, evdev.ecodes.KEY_SPACE]
    file = "/sys/class/leds/chromeos::kbd_backlight/brightness"
    keys_down = set()

    for event in keyboard.read_loop():
        if event.type == evdev.ecodes.EV_KEY:
            if event.value == 1:
                keys_down.add(event.code)
            elif event.value == 0:
                keys_down.discard(event.code)

            if keys_down == set(key_combo):
                f = open(file, "w+")
                cur = f.readline()
                if cur == "0\n":
                  f.write("50")
                elif cur == "100\n":
                  f.write("0")
                else:
                  f.write("100")

                f.close()

if __name__ == "__main__":
    detect_key_combination()
