#!/usr/bin/bash

acpi_listen > /tmp/acpi.log 2>&1 &

while inotifywait -e modify /tmp/acpi.log; do
  TABLET=$(tail -n 1 /tmp/acpi.log | grep '0000008A')
  echo which
  if echo "$TABLET" | grep '1$' ; then
    xinput disable "ACPI0C50:00 18D1:5028"
  else
    xinput enable "ACPI0C50:00 18D1:5028"
  fi
done
