#!/usr/bin/bash

monitor-sensor > /tmp/sensor.log 2>&1 &

while inotifywait -e modify /tmp/sensor.log; do
  ORIENTATION=$(tail -n 1 /tmp/sensor.log | grep 'orientation' | grep -oE '[^ ]+$')
  case "$ORIENTATION" in
  normal)
    xrandr --output eDP-1 --rotate normal 
    xinput set-prop "WCOM50C1:00 2D1F:5143" "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1 ;;
  bottom-up)
    xrandr --output eDP-1 --rotate inverted 
    xinput set-prop "WCOM50C1:00 2D1F:5143" "Coordinate Transformation Matrix" -1 0 1 0 -1 1 0 0 1 ;;
  right-up)
    xrandr --output eDP-1 --rotate right 
    xinput set-prop "WCOM50C1:00 2D1F:5143" "Coordinate Transformation Matrix" 0 1 0 -1 0 1 0 0 1 ;;
  left-up)
    xrandr --output eDP-1 --rotate left 
    xinput set-prop "WCOM50C1:00 2D1F:5143" "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1 ;;
  esac
done
