#!/bin/bash

monitor-sensor > /tmp/sensor.log 2>&1 &

while inotifywait -e modify /tmp/sensor.log; do
	ORIENTATION=$(tail -n 1 /tmp/sensor.log | grep 'orientation' | grep -oE '[^ ]+$')
	case "$ORIENTATION" in
	normal)
		   xrandr --output eDP-1 --rotate normal ;;
	bottom-up)
			xrandr --output eDP-1 --rotate inverted ;;
	right-up)
			xrandr --output eDP-1 --rotate right ;;
	left-up)
			xrandr --output eDP-1 --rotate left ;;
	esac
done
