#!/usr/bin/python3

from evdev import InputDevice
import time
from pynput.mouse import Button, Controller
from threading import Timer
import subprocess

dev = InputDevice('/dev/input/event4')
m = Controller()
lasttime = time.time()
rlasttime = time.time()
originaltime = lasttime
oldclickx = 0
oldclicky = 0


for event in dev.read_loop():

    if event.type == 3 and event.code == 47 and event.value == 1:
        rclicktime = time.time()
        if (rclicktime - rlasttime) < .5:
            rlasttime = rclicktime
        else:
            print("Two Finger tap.")
            subprocess.check_call(['xinput', '--disable', 'WCOM50C1:00 2D1F:5143'])
            #x2, y2 = m.position()  # Get the pointer coordinates
            m.click(Button.right, 1)
            subprocess.check_call(['xinput', '--enable', 'WCOM50C1:00 2D1F:5143'])
            rlasttime = rclicktime

    elif event.type == 1 and event.code == 330 and event.value == 1:
        clicktime = time.time()
        clickx, clicky = m.position
        if (clicktime - lasttime) < .5 and (abs(clickx - oldclickx) < 20) and (abs(clicky - oldclicky) < 20):
            print("Double click.")
            subprocess.check_call(['xinput', '--disable', 'WCOM50C1:00 2D1F:5143'])
            #x2, y2 = m.position()
            m.click(Button.left, 2)
            subprocess.check_call(['xinput', '--enable', 'WCOM50C1:00 2D1F:5143'])
            lasttime = originaltime
        else:
            lasttime = clicktime
        oldclickx = clickx
        oldclicky = clicky
